name: Build and deploy

## Place this in .github/workflows to run on push to main
## Ensure that workflow have write access in Settings > 

on:
  push:
    branches:
      - main
env:
  cache-version: v1
  GITHUB_PAT: ${{ secrets.GH_SECRET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: r-base:latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install dependencies with apt
      run: |
        apt-get update
        apt-get install -y texlive-latex-base texlive-fonts-extra git lmodern texlive-latex-recommended rsync

    - name: Restore cached R packages
      if: runner.os != 'Windows'
      uses: actions/cache/restore@v4
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-
        
    - name: Install dependencies with CRAN
      run: |
        options(repos = c(CRAN = "https://cran.r-project.org"))
        install.packages(c("knitr", "rmarkdown"), quiet=TRUE)
      shell: Rscript {0}

    - name: Cache R packages
      if: runner.os != 'Windows'
      uses: actions/cache/save@v4
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}

    - name: checkout
      uses: actions/checkout@v4
      
    - name: build
      run: |
        mkdir docs
        Rscript ghgenerate.R
        cp out/isc-proposal.html out/index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: $GITHUB_PAT
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
